cleff/cleff/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^profiles/',
        include('profiles.urls',
                namespace='profiles')),
    url(r'^',
        include('preapplanding.urls',
                namespace='preapplanding')),
    url(r'^engine/',
        include('engine.urls',
                namespace='engine')),
    url(r'^messaging/',
        include('messaging.urls',
                namespace='messaging'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cleff/engine/urls.py
from .views import update_comrades_view
from django.conf.urls import url

urlpatterns = [
    url(r'^$', update_comrades_view, name='update_comrades'),
]

cleff/preapplanding/urls.py
from django.conf.urls import include, url
from .views import landing, test

urlpatterns = [
    url(r'^$', landing, name='landing'),
    url(r'^test/$', test, name='test')
]

cleff/preapplanding/models.py
from django.db import models

# Create your models here.

cleff/preapplanding/views.py
from django.shortcuts import render

# Create your views here.


def landing(request):
    return render(request, 'preapplanding/index.html')


def test(request):
    return render(request, 'test/test.html')

cleff/preapplanding/templates/preapplanding/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<!-- move margin up negative margin top 'margin: -1.4em' if there is a white space at the top-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
   	<!-- ajax library cdn -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>



{% if request.user.musician %}
<script>


function initGeolocation() {
    if (navigator && navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
        } else {
            console.log('Geolocation is not supported');
        }
}
function errorCallback() {}
function successCallback(position) {
    var lat = position.coords.latitude.toString();
    var long = position.coords.longitude.toString();
    var coordinates = lat + ',' + long;
    console.log(coordinates);
    var coords = document.getElementById('coordinates');
    coords.value = coordinates;
    $.ajax({
        url: "{% url 'engine:update_comrades' %}",
        type: 'POST',
        data: {
            coordinates: coordinates,
            csrfmiddlewaretoken: '{{ csrf_token }}',
        }
    });

}



</script>

{% endif %}


<title>Cleff Now Under Development</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'minimal/theme/assets/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'minimal/theme/assets/css/main.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'minimal/theme/assets/css/font-awesome.min.css' %}">

    <script src="{% static 'minimal/theme/assets/js/jquery.min.js' %}"></script>


	
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'minimal/theme/assets/js/html5shiv.js' %}"></script>
      <script src="{% static 'minimal/theme/assets/js/respond.min.js' %}"></script>
    <![endif]-->
  </head>
  <body  onload="initGeolocation()" data-spy="scroll" data-offset="0" data-target="#theMenu" style="margin:-1.4em">
	{% if request.user.musician %}
  <!-- Ajax form start -->
  	<form action="{% url 'engine:update_comrades' %}" method="POST" id="position_form" >
       {% csrf_token %}
        <label>
            <input name="position" type="hidden" id="coordinates">
        </label>
	</form> <!-- Ajax form end -->
  {% else %}
    <body data-spy="scroll" data-offset="0" data-target="#theMenu">

  {% endif %}
	<!-- Menu -->
	<nav class="menu" id="theMenu">
		<div class="menu-wrap">
			<h1 class="logo"><a class="smoothScroll" href="#home">Minimal</a></h1>
			<i class="icon-remove menu-close"></i>
			<a href="#home" class="smoothScroll">Home</a>
			<a href="#about" class="smoothScroll">Why</a>
			<a href="#portfolio" class="smoothScroll">What to Expect</a>
			<a href="#contact" class="smoothScroll">Contact</a>
			<a href="https://www.facebook.com/cleffapp" target="_blank"><i class="icon-facebook"></i></a>
			<a href="https://twitter.com/CleffApp"><i class="icon-twitter"></i></a>
			<a href="mailto:cleffapp@gmail.com"><i class="icon-envelope"></i></a>
		</div>

		<!-- Menu button -->
		<div id="menuToggle"><i class="icon-reorder"></i></div>
	</nav>


	
	<!-- ========== HEADER SECTION ========== -->
	<section id="home" name="home"></section>
	<div id="headerwrap">
		<div class="container">
			<div class="logo">
				<img src="{% static 'minimal/theme/assets/img/logo.png' %}">
			</div>
			<br>
			<div class="row">
				<h1>Cleff Beta</h1>
				<br>
				<h3>Let's make music more sociable!</h3>
				<br>
				<br>
				<div class="col-lg-6 col-lg-offset-3">
				</div>
			</div>
		</div><!-- /container -->
	</div><!-- /headerwrap -->
	
	
	
	<!-- ========== ABOUT SECTION ========== -->
	<section id="about" name="about"></section>
	<div id="f">
		<div class="container">
			<div class="row">
				<h3>Why</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>
				
				<!-- INTRO INFORMATIO-->
				<div class="col-lg-6 col-lg-offset-3">
					<p>Have you ever wanted to start a band but can't find people near you that play what you do?</p>
					<p>Cleff App is a place to meet your neigbors and make music.</p>
					<p>At Cleff we understand that you get better over time, don't worry about old tracks</p>
					<p>when you have something new to show off your old tunes are history!</p>
				</div>
			</div>
		</div><!-- /container -->
	</div><!-- /f -->
	

	<!-- ========== CAROUSEL SECTION ========== -->	
	<section id="portfolio" name="portfolio"></section>

	<div id="f">
		<div class="container">
			<div class="row centered">
				<h3>SOME PROJECTS</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>
				
				<div class="col-lg-6 col-lg-offset-3">
					<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						<!-- Wrapper for slides -->
						<div class="carousel-inner">
							<div class="item active centered">
								<img class="img-responsive" src="{% static 'minimal/theme/assets/img/c1.png' %}" alt="">
							</div>
							<div class="item centered">
								<img class="img-responsive" src="{% static 'minimal/theme/assets/img/c2.png' %}" alt="">
							</div>
							<div class="item centered">
								<img class="img-responsive" src="{% static 'minimal/theme/assets/img/c3.png' %}" alt="">
							</div>
						</div>
						<br>
						<br>
						<ol class="carousel-indicators">
						    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
						    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
						    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
						</ol>
					</div>
				</div><!-- col-lg-8 -->
			</div><!-- row -->
		</div><!-- container -->
	</div>	<!-- f -->

	<!-- ========== CONTACT SECTION ========== -->
	<section id="contact" name="contact"></section>
	<div id="f">
		<div class="container">
			<div class="row">

				<h3>CONTACT US</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>
				
				<div class="col-lg-6 col-lg-offset-3">

					<p><a href="mailto:cleffapp@gmail.com">CleffApp@gmail.com</a></p>
					<p><button type="button" class="btn btn-primary">Donate</button></p>
				</div>
			</div>
		</div>
	</div>

	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'minimal/theme/assets/js/classie.js' %}"></script>
    <script src="{% static 'minimal/theme/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'minimal/theme/assets/js/smoothscroll.js' %}"></script>
	<script src="{% static 'minimal/theme/assets/js/main.js' %}"></script>
</body>
</html>